# Generated by Django 4.2 on 2023-04-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.CharField(max_length=500),
        ),
    ]
