# Generated by Django 4.2 on 2023-04-20 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="borrowing_id",
            new_name="borrowing",
        ),
    ]
